src/codeandphilosophy/codeandphilosophy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from registerStudent.views import ( 
	#AddStudentCreateView,
	AboutTemplateView,ContactTemplateView,
	RetrieveRegistrationTemplateView,
	ThanksTemplateView)

"""class based views are always CamelCased"""

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/$',AboutTemplateView.as_view(), name ='about'),
    url(r'^contact/$',ContactTemplateView.as_view(), name ='contact'),
    url(r'^retrieve/$',RetrieveRegistrationTemplateView.as_view(), name = 'retrieve'),
    url(r'^thanks/$',ThanksTemplateView.as_view(), name = 'thanks-with-regnumber'),
    url(r'^payments/', include('djstripe.urls', namespace="djstripe")),
    url(r'^$', include('registerStudent.urls', namespace='registerStudent')),
    #url(r'$',AddStudentCreateView.as_view(), name = 'add-student-create'),   
]

"""  url(r'$',AddStudentView.as_view()),  should be always at the end"""

src/codeandphilosophy/registerStudent/urls.py
from django.conf.urls import url

from .views import ( 
	AddStudentCreateView)

"""class based views are always CamelCased"""

urlpatterns = [
    url(r'',AddStudentCreateView.as_view(), name='add-student-create'), #don't include $ sign as this is already included in parent urls.py
] 

src/codeandphilosophy/registerStudent/models.py
import random
from django.core.urlresolvers import reverse
from django.db import models
from django.urls import reverse
from .validators import (
	validate_registration,
	#validate_name,
	#validate_location
	)

# Create your models here.
class StudentDetailsModel(models.Model):
	name = models.CharField(max_length=256,null=False,blank=False, verbose_name='Your name according to ID')
	location = models.CharField(max_length=256, null=False,blank=False)
	email =models.EmailField(max_length=256,blank=False,null=False, verbose_name= 'Valid email please!')
	registrationNumber = models.IntegerField(blank=False, null=False,default=random.randint(1, 9999999),
		unique=True, validators=[validate_registration])
	datetime = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	def __unicode__(self):
		return self.name

	def get_absolute_url(self): #will override the default method for success_url in createView
		return reverse('thanks-with-regnumber') #, kwargs={'slug': self.slug})


	'''class Meta:
		ordering = ['-updated','-timestamp'] #-updated: recently added item at front'''

src/codeandphilosophy/registerStudent/forms.py
from django import forms
from .models import StudentDetailsModel

'''class StudentDetailsForm(forms.Form):
	name = forms.CharField(required=True)
	location = forms.CharField(required=True)
	email =forms.EmailField(required=True)

	

	# TODO: write success implementation here.
	def send_email_on_success(self): # or send_email(self)
		pass'''


class StudentDetailsForm(forms.ModelForm):
    class Meta:
        model = StudentDetailsModel
        fields = ('name',
        	'location',
        	'email'
        )

    ''' Use this to reject obsene names
    	def clean_name(self):
     	name = self.cleaned_data.get('name')
     	if name == "Hello":
     	 	raise forms.ValidationError("Not a valid name")

     	return name 


     	def clean_location(self):
     	def clean_email(self):

     	'''
    

src/codeandphilosophy/registerStudent/views.py
import random
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import FormView, CreateView
from django.views.generic import TemplateView

from registerStudent.models import StudentDetailsModel
from registerStudent.forms import StudentDetailsForm
# Create your views here.

class AddStudentCreateView(CreateView):
	template_name = 'baseform.html' #template_name, form_class and success_url are django related variables
	form_class = StudentDetailsForm
	#model = StudentDetailsModel
	#fields = ('name', 'location', 'email','registrationNumber')
	#context_object_name
	#
	'''def get_object(self):	
		object = super(AddStudentCreateView,self).get_object()
		object['registrationNumber'] = random.randint(1, 9999999)
		object.save()
		print("Printing object now *******" + object)
		return object'''


	#def get_context_data(self, *args, **kwargs):
	#	context = super(ContactTemplateView,self).get_context_data(*args, **kwargs)

	#success_url = '/thanks/' #  defined with get_absolute_url in model

	'''If you use AddStudentFormView(FormView)
		def form_valid(self,form):		
		# This method is called when valid form data has been POSTed.
		
		if self.request.method == 'POST':
			#name = self.request.POST["name"] # OR self.request.POST.get("title")
			#location = self.request.POST["location"]
			#email = self.request.POST["email"]
			#StudentDetailsModel.objects.create(
		#		name = name,
		#		location = location,
		#		email = email
		#		)
			form = StudentDetailsForm(self.request.POST)
			if form.is_valid(): # For avoiding 'StudentDetailsForm' object has no attribute 'cleaned_data' -- Attribure Error
				StudentDetailsModel.objects.create(
					name = form.cleaned_data.get('name'),
					location = form.cleaned_data.get('location'),
					email = form.cleaned_data.get('email')
					)

			if form.errors:
				print(form.errors)

		form.send_email_on_success()
		#return super().form_valid(form) --> This is in Django 2.0
		return super(AddStudentFormView,self).form_valid(form)'''
	
class ThanksTemplateView(TemplateView):
	template_name = 'thanks.html'

class ContactTemplateView(TemplateView):
	template_name = 'contact.html'
	"""By default template view methods will give default implementation of other methods such 
	as get_context_data(). Use something like below to override those functions customizing them

	def get_context_data(self, *args, **kwargs):
		context = super(ContactTemplateView,self).get_context_data(*args, **kwargs)
		print(context)
		return context

	def get_object(self,*args,**kwargs)"""
	

class AboutTemplateView(TemplateView):
	template_name = 'about.html'
	#

class RetrieveRegistrationTemplateView(TemplateView):
	
	""" def get_queryset(self):
			print(self.kwargs)
			qs = StudentDetailsModel.objects.filter(name__iexact='' && email__iexact='')
			StudentDetailsModel.objects.get(id=RegNumberVariable) --> check DetailView for this immplementation
			return qs"""
	template_name = 'retrieve.html'

src/codeandphilosophy/registerStudent/templates/baseform.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Register Student</title>
	{% include 'snippets/css.html' %}
</head>
<body>

	<div class="container">
	{% include 'snippets/nav.html'%}
	<form method='POST'> {% csrf_token %} <!-- csrf prevent user input details to show up in the address bar when user clicks submit button. Also it overrides default GET to POST-->
		<h3>Please fill in the details to enroll!</h3>
		<!--input type="text" name="Name" placeholder="Student's Name"><br/>
		<input type="text" name="Date" placeholder="Choose date"><br/>
		<input id="emailAddress" type="email" name="Email" placeholder="Enter email"><br/-->
		{{ form.as_p }}
		<button type="submit">Submit</button>
		<button type="button">Retrieve</button>
	</form>
	</div>
	{% include 'snippets/js.html' %}
</body>
</html>

src/codeandphilosophy/templates/about.html
{% extends "base.html" %}

<div class="container">
	{% block title%}About{%endblock%}
	
	{% block content%}
		<h1>This is about About template.</h1>
	{% endblock %}

</div>

src/codeandphilosophy/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title> {% block title%} {% endblock %}</title>
		{% include 'snippets/css.html' %}
	</head>
	<body>
		<div class="container">
			
			{% include 'snippets/nav.html'%}
			{% block content %} {% endblock %}
		</div>

		{% include 'snippets/js.html' %}
	</body>
</html>

src/codeandphilosophy/templates/contact.html
{% extends "base.html" %}

<div class="container">
	{% block title%}Contact{%endblock%}
{% block content%}
	<br/><br/><div><h4>Email:<a href="mailto:ppentama@protonmail.com">@CodeAndPhilosophy</a></div></h4>	
{% endblock %}
</div>

src/codeandphilosophy/templates/retrieve.html
{% extends "base.html" %}

<div class="container">
	{% block title%}Retrieve{%endblock%}
	
	{% block content%}
		<h1>This is about Retrieve Registration template.</h1>
	{% endblock %}

</div>

src/codeandphilosophy/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

src/codeandphilosophy/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

src/codeandphilosophy/templates/snippets/nav.html
<h1>Welcome to Code And Philosophy!</h1>

<a href="{% url "registerStudent:add-student-create" %}">Register</a>
 <!--registerStudent:add-student-create is used because registerStudent has its own url and include()ed into main urls.py-->
<a href="{% url "retrieve" %}">RetrieveRegistration</a>
<a href="{% url "about" %}">About</a>
<a href="{% url "contact" %}">Contact</a>

src/codeandphilosophy/templates/thanks.html
{% extends "base.html" %}

<div class="container">
	{% block title%}Thank You!{%endblock%}
	
	{% block content%}
		<h1>Thank you for registering. This is your registration number: .</h1>
	{% endblock %}

</div>